# Generated by Django 4.1.1 on 2022-12-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='album_id')),
                ('album_title', models.CharField(max_length=100, verbose_name='album_title')),
                ('author_name', models.CharField(max_length=100, verbose_name='author_name')),
                ('release_date', models.DateField(verbose_name='release_name')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-album_id'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='song_id')),
                ('song_title', models.CharField(max_length=100, verbose_name='song_title')),
                ('author_name', models.CharField(max_length=100, verbose_name='author_name')),
                ('release_date', models.DateField(verbose_name='release_date')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'ordering': ['-song_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('customer_name', models.CharField(max_length=100, verbose_name='customer_name')),
                ('date', models.DateField(verbose_name='date')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.album', verbose_name='album_id')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_id'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.song', verbose_name='song_id'),
        ),
    ]
